# Inline configuration
# Level: Project (standalone)

branches:
  - main
  - name: beta
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "@semantic-release/exec"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
  - "@semantic-release/github"
